name: Trigger Vercel Deploy (via Deploy Hook)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger Vercel deploy
        env:
          HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$HOOK_URL" ]; then
            echo "❌ ERROR: VERCEL_DEPLOY_HOOK_URL secret is missing"
            exit 1
          fi

          echo "🚀 Calling Vercel deploy hook..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$HOOK_URL")

          echo "Hook HTTP status: $HTTP_STATUS"
          if [ "$HTTP_STATUS" -ge 400 ]; then
            echo "❌ Deploy hook returned error status $HTTP_STATUS"
            exit 1
          fi

          echo "✅ Deploy hook triggered successfully."
